// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import { TableSortController } from "stimulus-library"
application.register("table-sort", TableSortController)

import MultiselectController from "./multiselect_controller.js"
application.register("multiselect", MultiselectController)

import { Datepicker } from 'stimulus-datepicker'
application.register('datepicker', Datepicker)

import ModalController from "./modal_controller.js"
application.register("modal", ModalController)
