// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import { Datepicker } from "stimulus-datepicker"
application.register("datepicker", Datepicker)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import IconpickerController from "./iconpicker_controller"
application.register("iconpicker", IconpickerController)

import IntroController from "./intro_controller"
application.register("intro", IntroController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import MultiselectController from "./multiselect_controller"
application.register("multiselect", MultiselectController)

import { TableSortController } from "stimulus-library"
application.register("table-sort", TableSortController)