version: '3'
services:
  db:
    image: postgres:12
    ports:
      - "5431:5432"
    environment:
      POSTGRES_PASSWORD: postgres
  web:
    platform: linux/amd64
    build: .
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec bin/dev"
    volumes:
      - .:/kamp
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: .env
